export const GET_SOFAS_REQUEST = "GET_SOFAS_REQUEST";
export const GET_SOFAS_SUCCESS = "GET_SOFAS_SUCCESS";
export const GET_SOFAS_FAILURE = "GET_SOFAS_FAILURE";

export const GET_SINGLE_SOFA_REQUEST = "GET_SINGLE_SOFA_REQUEST";
export const GET_SINGLE_SOFA_SUCCESS = "GET_SINGLE_SOFA_SUCCESS";
export const GET_SINGLE_SOFA_FAILURE = "GET_SINGLE_SOFA_FAILURE";

export const ADD_TO_CART = "ADD_TO_CART";

export const DELETE_REQUEST = "DELETE_REQUEST";
export const UPDATE_REQUEST = "UPDATE_REQUEST";
export const POST_REQUEST = "POST_REQUEST";